site_name: Online Notebook

theme:
  name: material
  palette:
    - primary: custom
  features:
    - navigation.sections
    - navigation.footer

nav:
  - Home: index.md
  - Optics:
      - Overview: Optics/index.md
      - Lectures:
          - Lecture 1: Optics/Lectures/Opt_01_20_26.md
          - Lecture 2: Optics/Lectures/Opt_01_22_26.md
          - Lecture 3: Optics/Lectures/Opt_01_27_26.md
          - Lecture 4: Optics/Lectures/Opt_01_29_26.md
          - Lecture 5: Optics/Lectures/Opt_02_03_26.md
      - Homework:
          - HW 1: Optics/Homework/Optics_HW1.md
          - HW 2: Optics/Homework/Optics_HW2.md
  - Statistical Mechanics:
      - Overview: Statistical_Mechanics/index.md
      - Lectures:
          - Lecture 1: Statistical_Mechanics/lectures/Stat_01_20_26.md
          - Lecture 2: Statistical_Mechanics/lectures/Stat_01_22_26.md
          - Lecture 3: Statistical_Mechanics/lectures/Stat_01_27_26.md
          - Lecture 4: Statistical_Mechanics/lectures/Stat_01_29_26.md
      - Homework:
          - HW1: Statistical_Mechanics/homework/Statistical_Mechanics_HW1.md
          - HW2: Statistical_Mechanics/homework/Statistical_Mechanics_HW2.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition


extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
